version: "3"
networks:
    redis-cluster-net:
        external:
            name: redis-cluster-net

services:
  selenium-hub:
    image: selenium/hub:4.10.0-20230607
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      redis-cluster-net:
        ipv4_address: 192.168.200.100
  chrome:
    image: selenium/node-chrome:4.10.0-20230607
    shm_size: 1gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      redis-cluster-net:
        ipv4_address: 192.168.200.102
  firefox:
    image: selenium/node-firefox:4.10.0-20230607
    shm_size: 1gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      redis-cluster-net:
        ipv4_address: 192.168.200.103
  edge:
    image: selenium/node-edge:4.10.0-20230607
    shm_size: 1gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      redis-cluster-net:
        ipv4_address: 192.168.200.104