version: "3"
networks:
    redis-cluster-net:
        external:
            name: redis-cluster-net
            
services:
    server:
     image: yandex/clickhouse-server
     ports:
     - "18123:8123"
     - "19000:9000"
     - "19009:9009"
     
     ulimits:
      nproc: 65535
      nofile:
       soft: 262144
       hard: 262144
     volumes:
      - './.clickhouse-data/db:/var/lib/clickhouse/'
      - './config/users.xml:/etc/clickhouse-server/users.xml'
      - './config/config.xml:/etc/clickhouse-server/config.xml'
     networks:
       redis-cluster-net:
        ipv4_address: 192.168.200.203
