version: '3'

networks:
  redis-cluster-net:
    external:
      name: redis-cluster-net

services:
  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181
    networks:
      redis-cluster-net:
        ipv4_address: 192.168.200.71
  admin:
    image: cao2068959/dubbo-admin:2.7
    depends_on:
      - zookeeper
    ports:
      - 8080:8080
    environment:
      - admin.registry.address=zookeeper://zookeeper:2181
      - admin.config-center=zookeeper://zookeeper:2181
      - admin.metadata-report.address=zookeeper://zookeeper:2181
      - admin.registry.group=dubbo
      - admin.config-center.group=dubbo
      - admin.metadata-report.group=dubbo
      - admin.apollo.token=e16e5cd903fd0c97a116c873b448544b9d086de9
      - admin.apollo.appId=test
      - admin.apollo.env=dev
      - admin.apollo.cluster=default
      - admin.apollo.namespace=dubbo
    networks:
      redis-cluster-net:
        ipv4_address: 192.168.200.72