version: '3'

networks:
  nginx-cluster-net:
    external:
      name: nginx-cluster-net
services:
  ubuntu-ssh-container:
    image: ubuntu-ssh
    container_name: ubuntu-ssh01
    ports:
      - "2222:22"
      - "8080:80"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
      - "8085:8085"
      - "8086:8086"
      - "8087:8087"
      - "8088:8088"
      - "8089:8089"
      - "8090:8090"
      - "3306:3306"
      - "6379:6379"
      - "5672:5672"
      - "15672:15672"
    privileged: true
    networks:
      nginx-cluster-net:
        ipv4_address: 192.168.100.101
