version: '2'                                  # docker-compose 的版本

networks:
  redis-cluster-net:
    external:
      name: redis-cluster-net

services:                                     
  ghost:                                      
    image: ghost:5.49
    container_name: ghost             
    restart: always                           
    ports:                                    
      - '8080:2368'
    environment:                              # environment 是 image 的設定，依每個 image 會有不同選項，ghost 可以設定 url
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: root
      database__connection__password: oh_my_ody!
      database__connection__database: ghost
      # this url value is just an example, and is likely wrong for your environment!
      url: http://localhost:8080
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      NODE_ENV: development
    networks:
      redis-cluster-net:
          ipv4_address: 192.168.200.151