version: "3"
services:
 zookeeper:
  image: wurstmeister/zookeeper
  ports:
   - "19005:2181" 
 kafka:
  image: wurstmeister/kafka
  hostname: kafka
  ports:
   - "29092:29092"  
  environment:
   TZ: CST-8
   KAFKA_BROKER_ID: 3
   KAFKA_ADVERTISED_HOST_NAME: kafka
   KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
   KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:29092
   KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://127.0.0.1:29092
   KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
   KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
  links:
   - zookeeper